# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c97d7bfc64e446cdd7253a974cef58d70d85d40ca8af949bd140adcf83120382825e537f7dea673605be9d6710a2e4aa86de66695a1e7ffdbdedfcf86d838cd8

test:
  secret_key_base: f6b3dfc177ec5c67d3dd5d101baa524b0c15d486c2c36bebb01ff178a2771bfd214e9e28dd78208714093c2e95fe6749c1c275992ecb3636028bca06a30f1f3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
